configuration:
  provider: aws
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      default: true
      config:
        region: homelab
        s3Url: http://minio.minio.svc.cluster.local:9000
        s3ForcePathStyle: "true"
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: homelab

credentials:
  useSecret: true
  existingSecret: velero-credentials

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.0
    volumeMounts:
      - mountPath: /target
        name: plugins
