apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/falcosecurity/charts.git
      targetRevision: main
      path: charts/falco
      helm:
        valueFiles:
          - $values/kubernetes/falco/values.yaml
    - repoURL: https://github.com/mtstrong/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
