apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headscale
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/name: headscale
spec:
  project: default
  source:
    repoURL: https://github.com/mtstrong/homelab.git
    path: kubernetes/headscale
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: headscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
