#!/bin/bash
# GitHub Secrets Setup Guide
# This script provides instructions for setting up GitHub Secrets for Proxmox Terraform automation

set -e

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   GitHub Secrets Setup for Proxmox Terraform Automation       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "This script will help you set up GitHub Secrets needed for:"
echo "  ✓ Nightly drift detection"
echo "  ✓ CI/CD pipeline automation"
echo "  ✓ Safe credential management"
echo ""

echo "STEP 1: Navigate to GitHub Repository Settings"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://github.com/mtstrong/homelab"
echo "2. Click 'Settings' tab"
echo "3. In left sidebar, click 'Secrets and variables' → 'Actions'"
echo ""

echo "STEP 2: Create Required Secrets"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

SECRET_1_NAME="PROXMOX_TOKEN_ID"
SECRET_1_VALUE="terraform@pam!terraform"
echo "Secret #1: $SECRET_1_NAME"
echo "  Click 'New repository secret'"
echo "  Name: $SECRET_1_NAME"
echo "  Value: $SECRET_1_VALUE"
echo "  Click 'Add secret'"
echo ""

SECRET_2_NAME="PROXMOX_TOKEN_SECRET"
SECRET_2_VALUE="xxxxx-xxxxx-xxxxx-xxxxx"  # Your actual token secret
echo "Secret #2: $SECRET_2_NAME"
echo "  Click 'New repository secret'"
echo "  Name: $SECRET_2_NAME"
echo "  Value: $SECRET_2_VALUE  ← Keep this PRIVATE!"
echo "  Click 'Add secret'"
echo ""

SECRET_3_NAME="CLOUD_INIT_PASSWORD"
echo "Secret #3: $SECRET_3_NAME"
echo "  Click 'New repository secret'"
echo "  Name: $SECRET_3_NAME"
echo "  Value: (the cloudlaunch password you set - homelab2026)"
echo "  Click 'Add secret'"
echo ""

echo "STEP 3: Verify Secrets are Set"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "You should see 3 secrets listed:"
echo "  ✓ CLOUD_INIT_PASSWORD"
echo "  ✓ PROXMOX_TOKEN_ID"
echo "  ✓ PROXMOX_TOKEN_SECRET"
echo ""

echo "STEP 4: Test the Workflow"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://github.com/mtstrong/homelab/actions"
echo "2. Click 'Proxmox Drift Detection' workflow"
echo "3. Click 'Run workflow' → 'Run workflow' (green button)"
echo "4. Wait for job to complete (5-10 minutes)"
echo ""
echo "Expected results:"
echo "  ✅ terraform init - SUCCESS"
echo "  ✅ terraform validate - SUCCESS"
echo "  ✅ terraform plan - Shows no changes (or lists expected changes)"
echo ""

echo "STEP 5: Schedule Nightly Runs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The workflow is configured to run automatically every night:"
echo "  ⏰ Time: 2:00 AM UTC (adjust in .github/workflows/proxmox-drift-detection.yml)"
echo "  📍 Frequency: Daily"
echo ""
echo "Workflow file: .github/workflows/proxmox-drift-detection.yml"
echo "  Line 7: schedule cron expression"
echo ""
echo "To change schedule, modify the cron:"
echo "  - cron: '0 2 * * *'   # Changes go here"
echo "    ↑ ↑ ↑ ↑ ↑"
echo "    │ │ │ │ └─ Day of week (0-6, 0=Sunday)"
echo "    │ │ │ └─── Month (1-12)"
echo "    │ │ └───── Day of month (1-31)"
echo "    │ └─────── Hour (0-23, UTC)"
echo "    └───────── Minute (0-59)"
echo ""
echo "Examples:"
echo "  '0 9 * * 1-5'    # 9 AM UTC, Monday-Friday"
echo "  '0 6 * * *'      # 6 AM UTC, every day"
echo "  '*/30 * * * *'   # Every 30 minutes"
echo ""

echo "OPTIONAL: Set Up Email Notifications"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "GitHub will notify of workflow failures:"
echo "1. Settings → Notifications"
echo "2. Set 'Watching' to 'All Activity'"
echo "3. Check 'On failure' is enabled"
echo ""

echo "TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If workflow fails:"
echo ""
echo "❌ 'Error: Secrets not found'"
echo "  → Check all 3 secrets were added correctly"
echo "  → Verify exact names (case-sensitive)"
echo ""
echo "❌ 'timeout or connection refused'"
echo "  → Proxmox host may be unreachable from GitHub servers"
echo "  → Verify 'https://bd790i.local:8006' is publicly accessible"
echo "  → Or use a public IP instead of .local hostname"
echo ""
echo "❌ 'invalid token'"
echo "  → Verify token hasn't expired"
echo "  → Check token has required Proxmox permissions"
echo "  → Recreate token if needed"
echo ""

echo "✅ Setup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Your Proxmox infrastructure is now monitored for drift!"
echo ""
echo "Next steps:"
echo "  1. Add GitHub Secrets (see STEP 2 above)"
echo "  2. Test the workflow (see STEP 4 above)"
echo "  3. Monitor workflow runs in GitHub Actions tab"
echo "  4. Investigate any drift issues"
echo ""
echo "For more info, see: terraform/proxmox-prod/README.md"
echo ""
