---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: overseerr
  labels:
    app: overseerr
    app.kubernetes.io/instance: overseerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      nodeSelector:
        worker: "true"
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: seerr
        image: ghcr.io/seerr-team/seerr:v3.4.1
        env:
        - name: TZ
          value: America/Chicago
        ports:
        - containerPort: 5055
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: overseerr
          mountPath: /app/config
      volumes:
      - name: overseerr
        persistentVolumeClaim:
          claimName: overseerr
